ハラスメントについての冒頭文を翻訳。英語難しい。
PyLadiesTokyo/pyladies-handbook-translation pull request #14
Opened 2017-11-04 15:34 UTC by mahya8585

ガシガシ指摘お願いします

2017-11-04 15:34 UTC, mahya8585 commented
issue #6

2017-11-04 16:28 UTC, mahya8585 reviewed
my todo完了

2017-11-04 16:28 UTC, mahya8585 commented on MemberReference/ReportingHarassment/1_ReportingHarassment.md
[todo] タイトルの翻訳をする

2017-11-04 16:35 UTC, nobolis requested changes
コメントしましたー。よしなにお願いします。

2017-11-04 16:35 UTC, nobolis commented on MemberReference/ReportingHarassment/1_ReportingHarassment.md
> +PyLadiesはハラスメントを受けたことのある、または受けるであろうコミュニティメンバーの手助けになるよう、この章を作成しました。Pyladiesはメンバーに安全な場所を提供したいと考えているのです。
重要なことが前にあった方がわかりやすいと思うのと、現在完了の中の現在形なので、「受けた」メンバよりは「受ける」メンバなのかなと思ったので、2文目を前にもってきて、1文目を短くした以下のような書き方はいかがでしょうか。

```
Pyladiesはメンバーに安全な場所を提供したいと考えています。そのため、PyLadiesはハラスメントを受けるであろうコミュニティメンバーの手助けになるよう、この章を作成しました。
```

2017-11-07 04:41 UTC, mahya8585 commented on MemberReference/ReportingHarassment/1_ReportingHarassment.md
> +PyLadiesはハラスメントを受けたことのある、または受けるであろうコミュニティメンバーの手助けになるよう、この章を作成しました。Pyladiesはメンバーに安全な場所を提供したいと考えているのです。
ありがとうございます！いただいた文章のが良い感じなのでこちらの方向で修正します！

2018-04-01 14:03 UTC, okusama27 commented
transifexに移行したので、閉じます

https://www.transifex.com/pyladiestokyo/pyladies-handbook-translation/translate/#ja/memberpo/131949289

2018-04-01 14:03 UTC, closed without merging